export const lyricsCatalog = [
  { no: 1, title: "SOMA ZEFANIA", lines: [
    "1. Soma Zefania sura ya tatu",
    "Msitari wake ni kumi na nne ×2",
    "Imba ewe binti zayuni",
    "Pasa sauti na uchangamke",
    "2. Piga kinubi Pamoja na tari,",
    "Imba Halleluyah Halleluyah ×2",
    "3. Elohim amefuta dhambi zako,",
    "Na kufukuza adui zako mbali ×2",
    "4. Usiogope binti zayuni,",
    "Mkono wako usilegee ×2",
  ] },
  { no: 2, title: "YASHUA MASIHI ALIENDA", lines: [
    "1. Yashua masihi alienda,",
    "kutuandalia makao,",
    "akimaliza atarudi,",
    "(ili alipo nasi tuwepo) ×2",
    "Halleluyah miaka elfu moja,",
    "tutafurahi na masihi,",
    "machozi yote tuliyolia,",
    "(safarini atayapanguza)×2",
    "2. Ufalme huo wa yahshua,",
    "hautakuwa na huzuni,",
    "shetani naye atafungwa,",
    "(na Malaika katika kuzimu) ×2",
    "3. Simba naye atakula nyasi,",
    "mtoto anyonyaye atacheza,",
    "kwenye tundu la yule nyoka,",
    "(hakutakuwa madhara yoyote) ×2",
    "4. Mbwa mwitu naye atakaa,",
    "Pamoja na mwana kondoo,",
    "na chui atalala pamoja,",
    "(na mwana mbuzi halleluyah)×2",
    "5. Haki nayo itakuwa mshipi,",
    "wa kiuno chake ,masihi ,",
    "ufalme huo wa yahshua ,",
    "(hautakuwa na shinda yoyoye)×2",
    "6. Wamasihi tujitayarisheni,",
    "ili yahshua akija na ufalme,",
    "tutauridhi kwa furaha ,",
    "(furaha isiyo na mwisho)×2",
  ] },
  { no: 3, title: "NINATAMANI", lines: [
    "1. Ninatamani kumwona mwokozi,",
    "aliyeshinda kifo na mauti,",
    "wokovu wangu utakamilika ,",
    "nikimwona yahshua Bwana wangu.",
    "Nitase, nitasema ndiye bwana,",
    "Niliye, niliyemngoja sana,",
    "Ataru, atarudi kutawala,",
    "Na wale, wale wote waaminifu.",
    "2. Dunia sasa imeshaa zeeka,",
    "magonjwa mengi ajali ni nyingi,",
    "maasi mengi njaa nayo vita,",
    "inatupasa tukae tayari.",
    "3. Nikimwona yahshua bwana Wangu,",
    "machozi yangu atayapanguza,",
    "nitasahau shida za dunia,",
    "heri walio kuwa tayari.",
  ] },
  { no: 4, title: "YAHSHUA MESSIAH BWANA WETU", lines: [
    "1. Yahshua messia Bwana wetu,",
    "Alienda kutuandalia,",
    "Mji mzuri wa dhahabu,",
    "Nikiingia sitatoka kamwe.",
    "Yahshua wetu akirudi,",
    "Ataniambia njoo,",
    "Njoo njoo ewe mwanangu,",
    "Atanikaribisha kwake.",
    "2. Furahi binti wa zayuni,",
    "Bwana arusi yuaja kwako,",
    "Kutakuwa na karamu kubwa,",
    "Tukisherekea na yahshua.",
    "3. Kilio Pamoja na kuugua,",
    "Zitakimbia kabisa,",
    "Amani Pamoja na furaha,",
    "Ndizo zitajaa dunia.",
    "4. Yerusalem mji mwema,",
    "Uliojaa utukufu (wa bwana)",
    "Hakuna kuugua tena,",
    "Magonjwa yote yatatoeka.",
  ] },
  { no: 5, title: "SIKU MOJA", lines: [
    "1. Siku moja, tutamwona yahshua akirudi,",
    "Pamoja na Malaika",
    "(parapanda) parapanda italia,",
    "Wateule wamlaki Bwana yahsua.",
    "Nasi zote, tutarukaruka Kama ndama,",
    "Siku hiyo ikifika ,",
    "Tutapaa, tutapaa mawinguni kama ndege,",
    "Kumlaki Bwana yahshua.",
    "2. Wateule, walio makaburini,",
    "Watatoka, wamlaki Bwana Yahshua,",
    "Wateule, waliosalia hai,",
    "Watapaa, wamlaki Bwana Yahshua.",
    "3. Atakuja, na ujira mkononi,",
    "Kumlipa, kila mtu kazi yake,",
    "Tutaviikwa, taji nzuri ya ushindi,",
    "Tumeshinda, mambo yote ya dunia",
    "4. Siku hiyo, kila jicho litamwona,",
    "Akirudi, kama Bwana wa mabwana,",
    "Wenye dhambi, watalia oi oi,",
    "Wakiomba milima iwafunike.",
  ] },
  { no: 6, title: "VICARIUS FILII DEI", lines: [
    "1. Maisha yangu yote nampa bwana,",
    "Aliyeniokoa toka dhambini,",
    "Sitamuacha kamwe mwokozi wangu,",
    "Nitamtumikia hata milele. ×2",
    "Bwana Yahshua unipe nguvu,",
    "Za kukutumikia hata milele×2",
    "2. Deni yangu ya dhambi amesha-lipa,",
    "Na kwa kupigwa kwako mimi nimepona",
    "Alipokuwa pale juu ya mti,",
    "Mwokozi alisema yote yamekwisha",
    "3. Alipokuwa hapa ukimwenguni,",
    "Popote alienda alitenda mema,",
    "Magonjwa mbali mbali aliyaponya,",
    "Aliwaweka huru waliofungwa.",
    "4. Yahshua ni mchungaji maishani mwangu,",
    "Nikiwa naye mimi sitapungukiwa,",
    "Kwenye malisho mema huniongoza,",
    "Sitaogopa kamwe nikiwa naye.",
    "kwa kirumi, Alama ya",
    "mnyama ndio ya pope",
    "x2",
    "7. Jumlisha kwa kirumi,",
    "Ni mia sita na",
    "sitini na sita Jina",
    "la pope x2",
    "8. Kwani wa ndugu zangu,",
    "Siku ya kwanza ya",
    "juma jumapili, Ndiyo",
    "ya pope x2",
  ] },
  { no: 7, title: "KITABU CHA ISAIA", lines: [
    "1. Kitabu cha Isaiah,",
    "Mlango wa albaini,",
    "Ishirini na saba,",
    "Hadi thelathini na moja.",
    "Nani aliye kama wewe,",
    "Nami aliye kama wewe,",
    "Elohim wa Israeli,",
    "Hilo ndilo jina lake.",
    "2. Magoti yaliyolegea,",
    "Yeye huyafanya imara,",
    "Mikono isiyo na nguvu,",
    "Yeye huitia nguvu",
    "3. Elohim peke yake,",
    "Yeye ndiye awezaye",
    "Kuokoa wateule,",
    "Wakati wa mateso",
    "4. Ndugu na Dada zangu,",
    "Tunapopata mateso,",
    "Tumtumaini yahshua,",
    "Tumkimbilie Elohim",
    "5. Tukizitii amri,",
    "Na kuwa na Imani na yahshua,",
    "Wakati wa dhiki ukifika,",
    "Elohim atatuokoa.",
  ] },
  { no: 8, title: "PAULO ALIYETUMWA", lines: [
    "1. Paulu, aliyetumwa,",
    "Kuhubiria mataifa,",
    "Awambie mataifa,",
    "Waunganishwe na Israeli. ×2",
    "Tunyonye basi, yerusalem",
    "Ili tuonje neno lillilo nzuri. ×2",
    "2. Myahudi ana ziada gani,",
    "Kwanza asimamia neno,",
    "Ya pili alibarikiwa,",
    "Na baraka za milele. ×2",
    "3. Mti wa shamba, ni wa Israeli,",
    "Mzeituni mwitu mataifa,",
    "Yapasa tuache mila zetu,",
    "Tuunganishwe na Israeli. ×2",
    "4. Na tusome warumi tatu,",
    "Msitari wa kwanza na wa pili,",
    "Ili tujue, ni watu gani,",
    "Wanaosimamia neno. ×2",
  ] },
  { no: 9, title: "TUSOMENI ZABURI", lines: [
    "1. Tusomeni zaburi,",
    "Mia hamsini,",
    "Na uendelee hapo,",
    "Ili ufahamu.",
    "Tusifuni elohim baba,",
    "Kwa uwezo wake,",
    "Na matendo ya ajabu ametufanyia.",
    "2. Daudi alipokuwa",
    "Na waisraeli,",
    "Alimsifu elohim baba,",
    "Kwa uwezo wake.",
    "3. Paulu alipokuwa,",
    "korokoroni,",
    "Alimsifu elohim baba,",
    "Kwa uwezo wake.",
    "4. Danieli alipotupwa,",
    "Tunduni mwa simba,",
    "Alimsifu elohim baba,",
    "Kwa uwezo wake.",
    "5. Tukiwa duniani,",
    "Kuna mateso,",
    "Bali huko zayuni,",
    "Furaha milele.",
    "6. La mwisho,",
    "ndugu zangu tujitayarishe,",
    "Ili yahshua akirudi.",
    "tuwe tayari.",
  ] },
  { no: 10, title: "ZABURI HAMSINI NA MOJA", lines: [
    "1. Zaburi Hamsini na moja,",
    "Rehema zake Baba,",
    "Ni nyingi. ×2",
    "Rehema zake baba ni nyingi,",
    "Akamtoa mwana wake,",
    "Kwa upendo. ×2",
    "2. Musa aliupiga ule mwamba,",
    "maji yenye uhai yakatoka. ×2",
    "3. Masihi kwa siku ya vibanda,",
    "Akataja maji yale yenye uzima. ×2",
    "4. Masihi akamwambia mke wa samaria,",
    "Nitakupa maji yenye uzima.",
    "5. Hayo yote yanamaanisha,",
    "Roho mtakatifu tuliyopewa.",
  ] },
  { no: 11, title: "YOHANA TATU", lines: [
    "1. Yohana tatu kumi na sita,",
    "Upendo wa Elohim kwetu sisi,",
    "Aliupenda ulimwengu sana,",
    "Akamtoa mwana wake.",
    "(Ainuliwe), Ainuliwe Elohim baba,",
    "Fadhili zake ni za milele.",
    "2. Kama vile alivyompenda, Israeli,",
    "Akamchukia Esau,",
    "Ndivyo alinipenda mimi,",
    "Na kunifanya mwana wake.",
    "3. Nilikuwa mpenda anasa,",
    "Pia nilikuwa mkorofi,",
    "Yahshua masihi akaniokoa,",
    "Akaniosha kwa damu yake.",
    "4. Halleluyah tumsifu yahshua,",
    "Kwa kuwa ametuokoa,",
    "Na kutufanya wana wake,",
    "Upendo wake ni wa ajabu.",
  ] },
  { no: 12, title: "MWISHO WA DUNIA", lines: [
    "1. Mwisho wa dunia umefika,",
    "Bwana yahshua yu karibu kuja,",
    "Tutamlaki huko hewani,",
    "Turudi zayuni tukiimba.",
    "Asante yahshua kwa kutupenda,",
    "Wema wako hauna kipimo.",
    "2. Tunakutukuza bwana yahshua,",
    "Na kuliinua jina lake,",
    "Kwa vile uliturehemia,",
    "Tulipokuwa tumepotea",
    "3. Vita ni vikali safarini,",
    "Kati yetu naye ibilisi,",
    "Lakini silaha tumepewa,",
    "Tukiwa na yahshua tutashinda.",
    "4. Furaha amani tutapata,",
    "Tutawale Pamoja na yahshua,",
    "Nacho kifo kitaangamia,",
    "Milele daima halleluyah.",
  ] },
  { no: 13, title: "DUNIANI", lines: [
    "1. Duniani, mimi nasafiri,",
    "Naingoja, siku ile jipya,",
    "Ndipo ninaomba uvumilivu,",
    "Niyashinde, yote ya dunia.",
    "Njoo yahshua, njoo ninakungoja,",
    "Njoo leo, unipe Subira,",
    "Roho yangu, ijae amani,",
    "Niyashinde, yote ya dunia.",
    "2. Humtoa, mtu maskini,",
    "Mavumbini, ukamuinua,",
    "Ili ale, na wale wakuu,",
    "We ni mungu, sio mwanadamu.",
    "3. Hapo kale, palikuwa mtu,",
    "Jina lake, aliitwa batimayo,",
    "Akasikia, yahshua anapita,",
    "Akamwambia, yahshua nirehemu.",
    "4. Manyumbani, tukikosa amani,",
    "Matengano, vita majaribu,",
    "Yatupasa, tuungane mikono,",
    "Tuite yahshua, atupe amani.",
    "5. Kanisani, tukikosa amani,",
    "Matengano, vita majaribu,",
    "Yatupasa tuungane mikono,",
    "Tuite yahshua atupe amani.",
  ] },
  { no: 14, title: "ULIPAA", lines: [
    "1. Ulipaa mbinguni yahshua,",
    "Kutuandalia makao,",
    "Ukimaliza utarudi,",
    "Utukaribishe, ulipo.",
    "Kila tunapoyawaza,",
    "Makao haya, twaisubiri,",
    "Tarumbeta yako yahshua,",
    "Tukulaki we, mawinguni.",
    "2. Juu ya mlima zayuni,",
    "Na mbele ya kiti cha enzi,",
    "Tupatikane, tu wa-shindi.",
    "3. Sisi tu wadhaifu yahshua,",
    "Twakutazamia urudi,",
    "Tubadili miili ya unyonge,",
    "Utuvike ya utukufu.",
  ] },
  { no: 15, title: "HAMA WE", lines: [
    "1. Wakati wa kuteketezwa,",
    "Kwa sodoma na comora,",
    "Lutu Pamoja na wanawe,",
    "Waliambiwa wahame.",
    "Hama we, Hama mwenzangu hama,",
    "Hama toka babeli,",
    "Usikubali kuangamizwa,",
    "Pamoja na Babeli.",
    "2. Baba kamwambia Abraham,",
    "Uhame toka nchi yako,",
    "Uende nitakapokuonyesha,",
    "Ndiposa nikubariki.",
    "3. Baba kanena na musa,",
    "Hamisha watu wangu,",
    "Kutoka nchi ya utumwa,",
    "Uwapeleke kanani.",
    "4. Masihi alihama,",
    "Kutoka kwa wazazi wake,",
    "Aliamua Kwenda kuishi,",
    "Mlima wa mizeituni.",
    "5. Yakupasa Ee Ndugu na Dada,",
    "Uhame kwa Binti Babeli,",
    "Na uwe wa kupatanishwa,",
    "Na binti wa zayuni.",
  ] },
  { no: 16, title: "NINA FURAHA", lines: [
    "1. Nina furaha moyoni mwangu,",
    "Ninapomwimbia yahswa wangu,",
    "Hata kama ni shida na dhiki,",
    "Sitaogopa nitamwimbia.",
    "(kweli kweli) kabla sijalala mauti,",
    "Heri nimwimbie yahshua wangu,",
    "Na hata nikilala mavumbini,",
    "Nilale nikimngoja Bwana×2",
    "2. Wenye haki wengi wamelala,",
    "Lakini mimi ninatembea,",
    "Sina hata kitu cha kumpa,",
    "Lakini yeye ananipenda. ×2",
    "3. Kweli Bwana Yahshua anipenda,",
    "Nizionapo huruma zake,",
    "Kila siku ninatenda dhambi,",
    "Lakini yeye ananipenda. ×2",
  ] },
  { no: 17, title: "SIKU ZAJA", lines: [
    "1. Yahshua alipokuwa duniani,",
    "Aliwaambia wanafunzi wake,",
    "Mukae katika amri zangu,",
    "Nami nitawapa musaidizi.",
    "Siku zaja ndivyo asema Bwana,",
    "Nitakapowamiminia roho,",
    "Wana wao nao watatabiri,",
    "Na wazee nao wataota ndoto.",
    "2. Usimhuzunishe roho wa bwana,",
    "Maana ndiyo muhuri wa Elohim,",
    "Kwa wale watakaokombolewa,",
    "Siku hiyo ya kurudi kwa Yahshua.",
    "3. Siku ya Pentecost ilipofika,",
    "Wanafunzi walikuwa Pamoja,",
    "Kukaja uvumi toka mbinguni,",
    "(wote) wakajawa na roho mtakatifu.",
    "4. Tusaidie Elohim Baba wetu,",
    "Roho wako adumu ndani yetu,",
    "Ili siku ya kurudi kwa Yahshua,",
    "Pia nasi tupate okolewa.",
  ] },
  { no: 18, title: "NIKITAFAKARI", lines: [
    "1. Nikitafakari upendo wa Yahshua.",
    "Duniani sitarudi tena. ×2",
    "Yahshua, uniongoze,",
    "Duniani kuna majaribu tele. ×2",
    "2. Sitaona haya kukuimbia,",
    "Ingawa maadui wananizunguka. ×2",
    "3. Nilipokufuata Bwana Yahshua,",
    "Ulimwengu ulinidharau sana. ×2",
  ] },
  { no: 19, title: "NATANGAZA JINA", lines: [
    "1. Natangaza jina,",
    "Jina la ajabu,",
    "Jina la masihi,",
    "Yahshua mwana wa mungu.",
    "Sikieni jina,",
    "Jina la ajabu,",
    "Jina la masihi,",
    "Yahshua mwana wa Mungu.",
    "2. Filipu alihubiri,",
    "Kwa jina la Yahshua,",
    "Wagonjwa wakaponywa,",
    "Mapepo yakatoroka.",
    "3. Petero na Yohana,",
    "Walitaja jina,",
    "La Yahshua masihi,",
    "Kiwete akasimama.",
    "4. Ushindi tumepata,",
    "Kwa jina la Yahshua,",
    "Zayuni tutafika kwa jina la ajabu.",
  ] },
  { no: 20, title: "ZAYUNI NINAUTAMANI", lines: [
    "1. Zayuni ninautamani,",
    "Tutaishi naye Yahshua wetu,",
    "Tukimsifu Elohim wetu,",
    "Milele yote na milele.",
    "Tutafurahi siku ya mwisho,",
    "Masihi wetu akisha-rudi,",
    "Tutamlaki huko hewani,",
    "Kwa wimbo mpya wa zayuni.",
    "2. Miili nayo itabadilishwa,",
    "Iliyo ya magonjwa na kifo,",
    "Tutavikwa miili ya kiroho,",
    "Na majina mapya sis zote.",
    "3. Udhaifu wote utaisha,",
    "Huzuni na magonjwa na kifo,",
    "Itakuwa nchi ya amani,",
    "Pamoja na Elohim.",
    "4. Tutaishi huko kwa amani,",
    "Na manabii na mitume,",
    "Musa paulu hata eliya,",
    "Pamoja na Elohim.",
  ] },
  { no: 21, title: "SIKU YA KURUDI", lines: [
    "1. Siku ya kurudi kwake Yahshua,",
    "Hakuna mtu ajuaye,",
    "Kwa hivyo tujitakazeni,",
    "Tuingie yerusalem",
    "Halleluyah Halleluyah Halleluyah,",
    "Tutaimba tukishinda,",
    "Mambo ya hapa duniani,",
    "Kwa shangwe na vigelegele.",
    "2. Yohana aliuona,",
    "Mji mpya Yerusalem,",
    "Ukishuka toka mbinguni,",
    "Wateule waingie.",
    "3. Kwa mtu atalipwa,",
    "Kwa kazi aliyofanya,",
    "Tenda wema utapewa,",
    "Taji nzuri ya ushindi.",
    "4. Masihi Yahshua aliteswa,",
    "Kwa ajili ya dhambi zetu,",
    "Akapigwa mijeredi",
    "Tuingie Yerusalem.",
  ] },
  { no: 22, title: "SOMA ZABURI MIA MOJA", lines: [
    "1. Soma zaburi mia moja",
    "Ishirini na moja,",
    "Msaada wangu watoka wapi,",
    "Msaada Wangu u Kwa Bwana.",
    "Nitainua macho yangu,",
    "Nitazame milimani,",
    "Msaada wangu watoka wapi,",
    "Msaada wangu u kwa bwana.",
    "2. Hatasinzia akulindaye,",
    "aliye mlinzi wa Israeli,",
    "Bwana ndiye mlinzi wako,",
    "Uvuli mkono wa kuume.",
    "3. Atakulinda utokapo,",
    "Atakulinda uingiapo,",
    "Maana ndiye mlinzi wako,",
    "Tangu sasa hata milele.",
    "4. Jua halitakupiga mchana,",
    "Wala mwezi wakatiwa usiku,",
    "Atakulinda na mabaya,",
    "Atakulinda nafsi yako.",
  ] },
  { no: 23, title: "TAZAMA MBINGU NA NCHI", lines: [
    "1. Tazama mbingu na nchi kweli,",
    "Ni kazi yake mba wetu. ×2",
    "(neno) neno la Elohim liko hai,",
    "Neno la Elohim huokoa. ×2",
    "2. Neno la Elohim lilimjia nuhu,",
    "Nuhu akaijenga Safina. ×2",
    "3. Angalieni sabato zake Baba,",
    "Zote aliweka kwa neno lake. ×2",
    "4. Angalieni idi zake Baba,",
    "Zote aliweka kwa neno lake.",
    "5. Tazameni ndege wa angani,",
    "Wote waliwekwa kwa neno lake.",
    "6. Watu wote wapate kumjua masihi,",
    "Wote wapate kuokolewa.",
  ] },
  { no: 24, title: "KAMA WEWE UMEPATA NENO", lines: [
    "1. Kama wewe umepata neno,",
    "Litokalo Yerusalem,",
    "Hubiria Jirani yako,",
    "Ashikane na wa wayahudi.",
    "Soma, Biblia imeandikwa,",
    "Kwa pumzi ya Elohim,",
    "Yafaa kwa mafundisho,",
    "Kuongoza na kuonya watu.",
    "2. Nabii Isaiah alitabiri,",
    "Katika siku za mwisho,",
    "Mataifa wataunganishwa,",
    "Nawana wa Israeli.",
    "3. Tubu dhambi upate ubatizo,",
    "Kwa jina la Yahshua masihi,",
    "Upate ondoleo la dhambi,",
    "Upokee roho mtakatifu.",
    "4. Jihadhari manabii wa uongo,",
    "Wajao kama kondoo,",
    "Ndani yao ni mbwa mwitu,",
    "Kwa matendo utawatambua.",
  ] },
  { no: 25, title: "SIKIENI HABARI YA MWISHO", lines: [
    "1. Sikieni Habari ya mwisho,",
    "Naye Baba ndiye alisema,",
    "Neno lake kwa siku ya mwisho,",
    "Litatoka kule Yerusalem.",
    "Natusomeni kitabu cha Isaiah,",
    "Mbili fungu lake mbili tatu,",
    "Tutaona na neno la Elohim Baba,",
    "Litatoka kule yerusalem.",
    "2. Yahshua masihi alituma mitume,",
    "Waende wakahubiri injili,",
    "Itangazeni kwa mataifa yote,",
    "Kuanzia kule Yerusalem.",
    "3. Na kila mtu atakayeamini,",
    "Na kubatizwa kwa jina la Yahshua,",
    "Siku ya mwisho ataokolewa,",
    "Na kupata uzima wa milele.",
    "4. Soma mariko sura kumi na sita,",
    "Msitari wake ni kumi na saba,",
    "Ishara hizi zitawafuatia,",
    "Wale watakaoamini Yahshua.",
  ] },
  { no: 26, title: "ELOHIM MUNGU WA YAKOBO", lines: [
    "1. Elohim mungu wa yakobo,",
    "Aliyejaa utakatifu,",
    "Ukamilifu wake wa ajabu,",
    "Hatuwezi kuuelezea.",
    "Mshangilieni kwa furaha,",
    "Ametenda mambo ya ajabu,",
    "Ambayo sisi hatuelewi,",
    "Bali yeye anayaelewa.",
    "2. Ameishikilia dunia,",
    "Haiwezi ikatingizika,",
    "Mbingu na nchi shangilieni,",
    "Nayo Bahari yote ivume.",
    "3. Jina lake Baba wa majeshi,",
    "Lina nguvu haliwezi shindwa,",
    "Limewazingira watu wake,",
    "Ndilo mwamba tena ngao yao.",
  ] },
  { no: 27, title: "TAZAMENI PENDO", lines: [
    "1. Tazameni pendo la namna gani,",
    "Alilotupa Elohim,",
    "Kwamba tuitwe wana wake,",
    "Watakaoridhi ufalme na wanawe.",
    "Maana najua mtetezi wangu,",
    "Yeye yu hai na siku moja,",
    "Yeye atasimama juu ya nchi,",
    "Na pasipo na mwili wangu nitamwona.",
    "2. Kama vile walinzi wangojeavyo,",
    "Kupambazuke Ee Baba nakungoja,",
    "Na baada ya mwili huu kuharibiwa,",
    "Natamani nikuone upande wangu.",
    "3. Napigana vita vizuri vya Imani,",
    "Nishike uzima nilio-ahidiwa,",
    "Si kwa mwili na damu bali ni kwa Roho,",
    "Msaidizi wangu naomba usiniache.",
    "4. Mateso niliyo-nayo kwa wakati huu,",
    "Siwezi kuhesabu kuwa ni kitu,",
    "Kulinganisha na ule utukufu,",
    "Nitakaokabidhiwa nikishinda",
    "5. Nitajitahidi, nitajipa nguvu,",
    "Sitazimia maana yuko nami,",
    "Ahadi zake ni za milele,",
    "Alizoniahidi najua atanipa.",
  ] },
  { no: 28, title: "WAEFESO MLANGO WA PILI", lines: [
    "1. Waefeso mlango wa pili,",
    "Fungu lake kumi na mbili,",
    "Hadi ishirini na mbili,",
    "Rehema za elohim Baba×2",
    "Nitaimba kwa furaha,",
    "Nitasifu jina lako. ×2",
    "2. Ulimtuma Yahshua mwanao,",
    "Ili aje kwa upatanisho,",
    "Akakibomoa kiambaza,",
    "Cha dhambi kilichotutenga. ×2",
    "3. Kwa jamii ya waisraeli,",
    "Sisi tulikuwa mbali,",
    "Hatukuwa na tumaini,",
    "Wala Elohim duniani. ×2",
    "4. Elohim twakushukuru,",
    "Kwa rehema zake nyingi,",
    "Na Fadhili zako nyingi,",
    "Uliotudhihirishia. ×2",
  ] },
  { no: 29, title: "KAMA NDEGE WAMWIMBIAVYO", lines: [
    "1. Kama ndege wamwimbiavyo,",
    "Alfajiri na mapema,",
    "Napasa sauti hewani,",
    "Nimshukuru Elohim.",
    "Halleluyah Hosana ni furaha,",
    "Tufikapo mbele za bwana,",
    "Tutarukaruka kwa shangwe,",
    "Tukifurahia ushindi.",
    "2. Zaburi mia Hamsini,",
    "Musifuni Bwana kwa shangwe,",
    "Kwenye patakatifu pake,",
    "Yeye anastahili sifa.",
    "3. Daudi alimsifu Bwana,",
    "Akiwa na furaha tele,",
    "Hakuogopa ulimwengu,",
    "Ingawa alikuwa mfalme.",
    "4. Sitakoma kumsifu Bwana,",
    "Hata niwe kwa hali gani,",
    "Hata kwenye ufalme ujao,",
    "Nitamwimbia wimbo mpya.",
    "5. Musifu kwa hiari yako,",
    "Amekupa uhai bure,",
    "Na sauti ya kupendeza,",
    "Ambayo yamfurahisha",
  ] },
  { no: 30, title: "TUIMBE WIMBO", lines: [
    "1. Tuimbe wimbo tumsifu Elohim,",
    "Yeye aishiye milele na milele,",
    "Mbinguni na duniani hakuna mwingine,",
    "Anastahili sifa ila yeye.",
    "Ndiye ametupa nguvu tumsifu,",
    "Katupa sauti tumuimbie yeye,",
    "Sasa tuna uhai tumsifu,",
    "Na kwenye ufalme wake tutaimba.",
    "2. Malaika maelfu wanamsifu,",
    "Na wazee na viumbe nne hai",
    "Wakisema Baba wewe wastahili, Uketiye",
    "kwenye kiti cha enzi.",
    "3. Mfalme daudi alimsifu,",
    "Akiwa na furaha nyingi ndani yake,",
    "Alipogeuza saduku la bwana, Mikali",
    "alifanywa tasa kwa dharau.",
    "4. Walimsifu walipotupwa motoni,",
    "Mfalme kashangaa kuona wanne,",
    "Alipofahamu ni mwana wa mungu,",
    "Akamtukuza mungu wa Danieli.",
    "5. Yohana aliona umati mkubwa,",
    "Wamejivika na mavazi meupe,",
    "Wakiwa na matawi wakimsifu,",
    "Wimbo wa musa na wa mwana kondoo.",
  ] },
  { no: 31, title: "SOMENI UFUNUO ISHIRINI", lines: [
    "1. Someni Ufunuo Ishirini,",
    "Moja Uendelee Mpaka Mwisho X2",
    "Tuingiapo Yerusalemu",
    "Ishukao Twaimba Halleluyah,",
    "Halleluyah X2",
    "2. Shetani Atafungwa",
    "Yahshua Akija, Miaka",
    "Elfu Moja Itimie X2",
    "3. Miaka Elfu Moja Ikitimia",
    "Shetani Afunguliwe, Awadanganye X2",
    "4. Shetani",
    "Atawadanganya",
    "Mataifa Wote Wa",
    "Pembe Nne Za Dunia",
    "X2",
    "5. Soma Tena Ufunuo,",
    "Kumi Na Tatu, Funga",
    "Kumi Na Nane",
    "Ufahamu X2",
  ] },
  { no: 32, title: "YULE YOHANA", lines: [
    "1. Yule yohana mtume",
    "wa yahshua,",
    "Alionyeshwa maajabu",
    "ya mwisho,",
    "Alionyeshwa na",
    "bwana yahshua,",
    "Alipokuwa kiziwa",
    "pattimo.",
    "Heri asomae ufunuo huo.",
    "Na kuyashika, yaliyo andikwa x2",
    "2. Toka mlango huo",
    "wa kwanza, Mpaka",
    "watatu, makanisa",
    "saba, Hayo",
    "alifananishwa na",
    "jina la, Nya taa saba",
    "za dhahabu.",
    "3. Mlango wan ne, kiti",
    "cha enzi, Mlango wa",
    "tano, kitabu cha ajabu,",
    "Mlango wa sita farasi",
    "wan ne, Mlango wa",
    "saba muhuri wa mungu.",
    "4. Kumi na mbili binti",
    "wa zayuni, kumi na",
    "saba binti wa babeli,",
    "kumi na tatu",
    "Wanyama wawili",
    "kumi nan ne ufalme",
    "wa sayuni.",
    "5. Kumi na sita mapigo",
    "ya mungu, Kumi na",
    "nane tokeni babeli,",
    "Kumi na tisa arusi ya",
    "bwana, Ishirini na",
    "mbili usiyaongeze.",
  ] },
  { no: 33, title: "YOHANA MTUME", lines: [
    "1. Yohana mtume wa",
    "yahshua messia,",
    "Aliyejulishwa yatakayo",
    "tokea, Nyakati za",
    "mwisho,",
    "Watu wa Elohim,",
    "wajitayarishe,",
    "Kuingia zayuni.",
    "Elohim baba na atukuzwe,",
    "Kwa kutufunulia siri ya ufalme x2",
    "2. Mnyama wa kutisha",
    "alionekana Akitoka",
    "majini na pembe",
    "zake, Na mwilini",
    "mwake ameandikwa,",
    "Majina ya kumkufuru yeye aliye juu.",
    "3. Vichwa vyake ni saba,",
    "huyo mnyama, na juu ya",
    "pembe zake taji za",
    "ufalme,",
    "na tazama kichwa- kimoja",
    "cha zile saba, kilikuwa na",
    "jeraha y amauti.",
    "4. Ufunuo kumi na tatu",
    "soma, Utayaelewa",
    "maajabu ya mwisho.",
    "Na mnyama huyo ndiye",
    "warumi, Soma utaelewa",
    "maajabu ya mwisho.",
    "5. Kanisa la Elohim",
    "limefananishwa, Na",
    "binti wa zayuni soma",
    "utaelewa, Kanisa la",
    "shetani",
    "limefananishwa,",
    "Na binti wa babeli mama wa makahaba.",
    "6. Tokeni babeli, kwake",
    "huyo mnyama,",
    "Msiangamizwe na",
    "bwana wa majeshi,",
    "Anaitana- tokeni Babeli,",
    "Msiangamizwe pamoja",
    "naye.",
  ] },
  { no: 34, title: "BASI NDUGU ZANGU", lines: [
    "1. Basi ndugu zangu",
    "wapendwa,",
    "Ninawaonea",
    "shauku,",
    "Furaha yangu",
    "naye taji,",
    "Simameni",
    "katika bwana,",
    "Furahini katika bwana, Upole",
    "ujulikane,",
    "Kwa kuwa yahshua yu",
    "karibu, Msisumbukie ya",
    "dunia.",
    "2. Na amani ya",
    "mungu baba,",
    "Ipitayo akili",
    "zote,",
    "Itawahifadhi",
    "mioyo,",
    "Yenyu yote ndani ya yahshua.",
    "3. Kukesha katika kusali,",
    "Na kuomba na",
    "kushukuru, Haja",
    "zenu zijulikane,",
    "Mbele zake mwenyezi mungu.",
  ] },
  { no: 35, title: "BWANA MUNGU AKASEMA", lines: [
    "1. Bwana mungu",
    "akasema,",
    "Ambia Israeli,",
    "Wataishika",
    "sabato, Kama",
    "nilivyo amuru.",
    "Kumbukeni- Kumbukeni sana,",
    "Siku ya",
    "sabato, Ni",
    "siku",
    "takatifu,",
    "Nani siku ya bwana.",
    "2. Bwana mungu",
    "aliumba,",
    "Mbingu na",
    "dunia,",
    "Na vyote",
    "vilivyoma,",
    "Muda wa",
    "siku sita.",
    "3. Utafanya",
    "kazi yako,",
    "Muda wa",
    "siku sita,",
    "Lakini siku",
    "ya saba, Ni",
    "sabato ya",
    "bwana.",
    "4. Bwana mungu",
    "aliweka, Siku",
    "ya sabato,",
    "Iwe ndiyo",
    "ishara, Kati",
    "ya bwana",
    "nasi.",
    "5. Bwana",
    "akaitakasa,",
    "Siku ya",
    "sabato, Pia",
    "akapumzika",
    ", Bwana",
    "akaibariki.",
  ] },
  { no: 36, title: "TWAINGOJEA SIKU YA BWANA", lines: [
    "1. Twaingojea siku",
    "ya bwana, Yaja",
    "uppesi kwa",
    "haraka,",
    "Tutamuona",
    "akirejea,",
    "Tena hapa ulimwenguni.",
    "Tutafurahi",
    "tukimuona,",
    "Tukiyashinda",
    "majaribu, Atuongoze",
    "twende sayuni",
    "Tutaishi naye milele.",
    "2. Tunakusifu",
    "mwokozi yahshua",
    "Kwa wema na",
    "Fadhili zako, Pokea",
    "sifa na utukufu,",
    "Na uhimidiwe milele.",
    "3. Itakuwa ni hoja",
    "na shida, kwa",
    "wale wasio,",
    "okoka",
    "bali kwa wale",
    "wamwaminio, iwe",
    "ni furaha na",
    "shangwe.",
    "4. Ibadilishe",
    "mienendo yako,",
    "Ufuate haki na",
    "ukweli,",
    "Ujiepushe na",
    "dhambi zote, Na",
    "atadumu ndani",
    "yako.",
  ] },
  { no: 37, title: "ELOHIM BABA MWENYEZI", lines: [
    "1.Elohim baba",
    "mwenyezi,",
    "Muumba wa",
    "mbuingu nan chi,",
    "Bahari na",
    "vilivyomo,",
    "Muweza wa mambo yote.",
    "Halleluyah tumsifu Elohim",
    "(Baba) Katika patakatifu",
    "pake,",
    "Katika anga la uweza",
    "wake, Daima Baba",
    "tutakusifu. X2",
    "2. Mbingu nazo za",
    "hubiri, Utukufu",
    "wake Elohim,",
    "Na anga nalo",
    "laitangaza, Ile",
    "kazi ya mikono",
    "yake.",
    "3. Jua mwezi nazo nyota,",
    "Na ndege wote wa angani,",
    "Na Wanyama wote",
    "wa kondeni, Hivyo",
    "vyote baba ni kazi",
    "yako.",
    "4. Elohim ndiye",
    "baba yetu, Na",
    "ndiye atupeaye",
    "nguvu, Na mimi",
    "nitamshukuru,",
    "Kwa kweli baba",
    "nitakusifu.",
    "5. Tumwimbie",
    "Baba Elohim,",
    "Katika patakatifu",
    "pake,",
    "Hiyo ndiyo ile",
    "heshima kwake,",
    "Kwa wote wateule",
    "wake.",
  ] },
  { no: 38, title: "FADHILI ZA BWANA", lines: [
    "1. Fadhili za bwana",
    "nitaziimba, Milele",
    "kwa kinywa",
    "change,",
    "Nitavijulisha",
    "vizazi vyote,",
    "Uaminifu wako.",
    "Mshukuruni",
    "mshukuruni,",
    "Mshukuruni Elohim",
    "Baba, Maana Fadhili",
    "zake mungu, Ni za",
    "milele.",
    "2. Mkono wa mungu ni",
    "mwenye, uwezo Mkono",
    "wa mungu una nguvu,",
    "Mkono wa mungu",
    "umetukuka,",
    "Nitavijulisha vizazi",
    "vyote.",
    "3. Nchi na mbingu ni",
    "mali yako,",
    "Ulimwengu nav yote",
    "uvijazavyo, Ni wewe",
    "uliopigapiga mizingi,",
    "Nitavijulisha vizazi",
    "vyote.",
    "4. Haki na hukumu",
    "ndio msingi, Wa",
    "kiti chako,",
    "Fadhili za kweli",
    "zahudhulia, Mbele",
    "ya uso wako.",
  ] },
  { no: 39, title: "DUNIANI KUNA GIZA (PRAISE OR", lines: [
    "PRAYERS)",
    "1. Duniani kuna giza",
    "kubwa, Nuru ya",
    "ulimwengu ni",
    "masihi, Huangaza",
    "kwa utukufu wake,",
    "Kwa wale waliitao",
    "jina lake.",
    "Mafichoni mafichoni",
    "twende, Mafichoni pa",
    "wokovu wake,",
    "Mwokozi Yahshua",
    "ndie, Ngome imara,",
    "Daima milele mafichoni.",
    "2. Dhambi zangu nazitwika",
    "kwake, Ndiye mwana",
    "kondoo pekee wa baba,",
    "Anitakaza na mawaa",
    "yote,",
    "Niwe safi mbele zake bwana.",
    "3. Haja zangu",
    "naziweka kwake,",
    "Utimilifu wote uko",
    "kwake, Aniponya",
    "na magonjwa yote,",
    "Roho yangu",
    "kaiweka huru.",
    "4. Ingawa maadui ni wengi,",
    "Bwana Yahshua u ngao",
    "pande zote, Usiwape",
    "adui wangu ushindi,",
    "Ni inue, wanapo nidunisha.",
  ] },
  { no: 40, title: "JIANDAENI KUJA MASIHI", lines: [
    "1. Jiandaeni kuja kwa",
    "Yahshua Messiah Aliye-",
    "kuwapo na aliyepo,",
    "Atakaye-kuja juu ya",
    "mawingu,",
    "Kutuchukuwa toka",
    "majaribuni x2",
    "Ninatamani ushindi wako",
    "Yahshua, Nishike mkono,",
    "kuna utelezi, Niziweze nguvu",
    "za yule mwovu,",
    "Kwa roho wako, mimi nitasimama x2",
    "2. Yohana aliishi kwa Imani,",
    "Katika Yahshua hadi",
    "mwisho wake,",
    "Aliposhinda",
    "alionyesha,",
    "Ufalme wa Yahshua tunaongojea. X2",
    "3. Na uona mji",
    "mtakatifu,",
    "Yerusalemu,",
    "ukishuka duniani,",
    "Ukitoka mbinguni",
    "kwa Elohim,",
    "Ni sisi tuliandaliwa x2sisi tuliandaliwa x2",
    "4. Tutafurahi",
    "tutakaposhinda ya",
    "duania, Yahshuakirudi,",
    "tutaimba kwa",
    "shangwe na furaha,",
    "Huyu ndiye",
    "tuliemngoja.",
    "5. Atakae shinda",
    "ataitanishwa nami,",
    "Nami nitakuwa,",
    "Elohim wake",
    "Naye atakuwa kweli yu",
    "mwanangu, Katika",
    "ufalme huo wa amani",
    "x2",
    "6. Twakusihi uliye",
    "tukomboa Uyadumishe",
    "majina katika kile kitabu,",
    "Cha uzima,",
    "Ili tudumu tukikupendeza x2",
  ] },
  { no: 41, title: "KATIKA UFUNUO", lines: [
    "1. Katika ufunuo- wa yohana",
    "kisiwani, Yohana",
    "alimuona- mnyama wa",
    "ajabu. X2",
    "Danieli ni saba, soma kumi na",
    "saba, Tumefunuliwa mnyama",
    "ni ufalme x2",
    "2. Yohana alimwona- mnyama",
    "wa ajabu, Mwenye pembe",
    "kumi na pia vichwa saba. X2",
    "3. Malaika akasema- ni",
    "ufalme wan ne, Hapa",
    "duniani- ambao ni",
    "warumi x2",
    "4. Jina la mnyama – viarius Fili Dei,",
    "Hivyo ni kusema mia sita sitini na sita x2",
    "5. Ufalme huo – utatoa sharia,",
    "Usifanye biashara- bila chapa ya mnyama x2",
  ] },
  { no: 42, title: "PETERO LISHA KONDOO WANGU", lines: [
    "1. Tusome yohana sura ishirini",
    "na moja, aya ya Kumi na tano",
    "hadi ishirini na tano, ndipo",
    "Tuelewe kisa cha petero",
    "anena na messiah Juu ya",
    "kondoo wake x2",
    "(petero petero Lisha kondoo",
    "wangu) x2 Petero kuambiwa",
    "tena mara ya tatu, Huku",
    "kushangaa kuna nini Bwana?",
    "Ninakupenda sana ewe messiah wangu x2",
    "2. Yahshua alipokuwa kaisaria filipi,",
    "Wanafunzi kuuliza watu wasemaje?",
    "Mimi ndiye nani? Wengine ni Elijah,",
    "petero asema wewe ndiye Yahshua x2",
    "3. Kule gethsemane, mlima",
    "wa mizeituni, Petero na",
    "yakobo pamoja na yohana,",
    "Maombi faraghani",
    "wakutwa na majeshi,",
    "Petero akata sikio la",
    "mariko. X2",
  ] },
  { no: 43, title: "PETERO WA YOHANA", lines: [
    "1. Petero wa yohana- alijaribu",
    "kupita juu ya maji, Na akazama",
    "x2",
    "Nishike mkono Bwana- nishike",
    "mkono Nishike mkono Bwana-",
    "nisianguke, Mpaka sayuni",
    "Bwana- mpaka sayuni Mpaka",
    "sayuni Bwana- Yerusalemu x2",
    "2. Yahshua alimjibu- ewe petero",
    "ungekuwa na Imani Haungezama",
    "x2",
    "3. Chanzo chake Imani- ni",
    "kusikia na kufanya, Mapenzi",
    "ya Elohim x2",
    "4. Faida yake Imani- tunda la",
    "roho kuishi kwa Amani na",
    "upendo x2",
    "5. Kutenda dhambi kama-",
    "umebatizwa, Umefanya",
    "makosa y amauti x2",
  ] },
  { no: 44, title: "SOMENI EZEKIELI 5:5", lines: [
    "1. Someni ezekieli hapo tano, tano,",
    "Ili tuelewane ujumbe hutoka wapi? X2",
    "Asante Elohim, kuchagua",
    "Yerusalem, Kuchagua Yerusalem",
    "ukaweka jina lako. X2",
    "2. Daudi alitunza amri za",
    "Elohim, Aliimba sana",
    "akiwa na furaha. X2",
    "3. Imbeni",
    "Hossana,",
    "Mwokozi",
    "atarudi,",
    "Akirudi Hossanah",
    "tutasema Hossanah, Ewe",
    "muumba wetu",
    "tumekungoja sana x2",
  ] },
  { no: 45, title: "AYUBU 1:1", lines: [
    "1. Tusomeni Ayubu sura",
    "ya kwanza, Mstari wa",
    "kwanza Subira ayubu.",
    "X2",
    "Avumiliaye kama",
    "Ayubu, Atapata taji,",
    "Taji la uzima.x2",
    "2. Mke wake Ayubu alimsihi",
    "amtukane Elohim, Apate kufa",
    "x2",
    "3. Masihi aliteswa",
    "Duniani bila kosa,",
    "Lolote, tuwe kama",
    "yeye, x2",
    "4. Tupatapo mateso",
    "Duniani,",
    "Tumkumbuke masihi",
    "aliyetuita x2",
  ] },
  { no: 46, title: "UAMINIFU WA BWANA", lines: [
    "1. Uaminifu wa",
    "bwana, Ni wa",
    "ajabu sana",
    "Yeye hachelewi kutimiza ahadi. X2",
    "Elohim Baba wetu, Baba",
    "mwaminifu Yeye ni",
    "mwaminifu, Baba mwaminifu",
    "2. Sodoma na Gomora",
    "iliangamizwa kwa",
    "Uaminifu wa Bwana",
    "kamponya lutu. X2",
    "3. Kuna kinywa cha Nabii Isaya,",
    "Baba alisema injiri itahubiriwa toka Yerusalem. X2",
    "4. Wathesalonike wa pili",
    "mlango wa tatu, Mstari",
    "wake wa tatu, soma",
    "ufahamu. X2",
  ] },
  { no: 47, title: "UKIANGALIA DUNIA HII", lines: [
    "1. Ukianga;lia",
    "dunia hii,",
    "Utaiona",
    "imepinduka,",
    "Jambo hili",
    "litatuonyesha,",
    "Kwamba messiah yuko njiani x2",
    "Ee ndugu kaza mwendo, shetani anakazana Siku",
    "za mwisho,",
    "Tukishinda sayuni tutafurahi. X2",
    "2. Tuvumilie majaribu,",
    "Ili tupite njia",
    "nyembamba,",
    "Linatuonyesha njia",
    "ile pan ani ya Muovu",
    "yule shetani x2",
    "3. Ndugu yangu lilia",
    "Bwana, Atasikia",
    "kilio chako,",
    "Tukisoma na",
    "kutafakari, Roho",
    "wa Yahshua",
    "atatujia x2",
    "4. Yaliandikwa na",
    "manabii, Mengi",
    "haya yametimia,",
    "Jambo hili",
    "linatuonyesha,",
    "Kwamba messiah yuko njiani, x2",
  ] },
  { no: 48, title: "BINTI WA ZAYUNI", lines: [
    "1. Binti wa sayuni",
    "alionekana, Katika",
    "ufunuo akiwa na",
    "taji, Tena amevaa",
    "vazi la kitani,",
    "Vazi la kitani ni matendo ya haki.",
    "Kanisa la bwana",
    "litaokolewa Siku hiyo",
    "wewe utakuwa wapi",
    "2. Hilo ni kanisa la",
    "Yahshua Mesia,",
    "Lishikalo amri na Imani",
    "ya Yahshua, Heri wale",
    "wote walio alikwa",
    "Katika kalamu ya mwana kondoo.",
    "3. Nyoka na mnyama",
    "waliifanya vita Kwa",
    "binti sayuni naye",
    "akashinda, Baada ya",
    "kushinda alionekana,",
    "Akimsifu Baba kwa",
    "wimbo wa musa.",
    "4. Baada ya kumwona",
    "binti wa sayuni, Yohana",
    "alimwona binti wa",
    "babeli, Akiongoza",
    "ulimwengu wote,",
    "Kwenye njia pana ile ya",
    "upotevu.",
    "5. Binti wa babeli",
    "alipewa jina, Babeli",
    "mkuu mama wa",
    "makahaba, Sauti",
    "ikasema tokeni Babeli,",
    "Kimbilia kanisa la",
    "Yahshua mesia.",
    "6. Msipo sikia na",
    "kutoka babeli,",
    "Mtaangamizwa",
    "kwenye viberiti,",
    "Wasio amini na",
    "wachukizao, Wote",
    "watakufa mauti ya",
    "pili.",
  ] },
  { no: 49, title: "ELOHIM AKUPENDA", lines: [
    "1. Ndugu Elohim",
    "akupenda, Ndiposa",
    "akamtoa",
    "mwanawe,",
    "Afee juu mtini ndiposa tupate wokovu.",
    "Msifu muumba wako",
    "msifu, Wakati ulio na",
    "nguvu, Kwani ngambo",
    "ya kaburi, Hakuna",
    "kumlipa tena.",
    "2. Wengi walio wa",
    "dunia, Wafuata",
    "mambo ya dunia,",
    "Wamesahau",
    "muumba wao,",
    "Fikira zao ni",
    "anasa.",
    "3. Tembea uone",
    "wagonjwa,",
    "Hawana nguvu za",
    "kumsifu, Wewe",
    "ulio na nguvu,",
    "Msifu kwa huo",
    "uzima.",
    "4. Mkumbuke Elohim",
    "muumba wako, Siku za",
    "ujana wako,",
    "Kabla haijaja",
    "siku, Wakati",
    "utakuwa",
    "dhaifu.",
  ] },
  { no: 50, title: "TAZAMENI MAAJABU", lines: [
    "1. Tazameni maajabu",
    "ya bwana, Alifanya",
    "akiwa duniani,",
    "Halleluyah yeye ni wa",
    "ajabu Jina lake ten ani",
    "la ajabu.",
    "2. Popote alienda",
    "Yahshua, Aliponya",
    "magonjwa",
    "mbalimbali,",
    "3. Kuja kwake",
    "kutakuwa ajabu,",
    "Mbingu nan chi",
    "zitatetemeka.",
    "4. Kuzaliwa kwake pia",
    "ni kwa ajabu",
    "Kulikuwa na nyota",
    "mashariki.",
    "5. Lazaro yule aliye",
    "lala, Yahshua",
    "akaja akamfufua.",
  ] },
  { no: 51, title: "EE BWANA", lines: [
    "1. Ee Bwana Elohim ni",
    "nani atakaye Kaa",
    "katika hema yako,",
    "Nani afanyae maskani",
    "yake katika, Kilima",
    "chako kitakatifu.",
    "Ooh Halleluyah tumsifu",
    "Elohim Ooh Halleluyah",
    "tumuinue Elohim Ooh",
    "Halleluyah tumtukuze",
    "Elohim",
    "Kwa kutufundisha njia zake za kweli.",
    "2. Ni Daudi aliuliza",
    "Elohim,",
    "Akamjibu ni mtu",
    "aendae,",
    "Kwa ukamilifu, na kutenda haki,",
    "Katika mambo yote, asemaye kweli kwa",
    "moyo wake.",
    "3. Asiyesingizia kwa ulimi wake,",
    "Wala hakumtenda jirani",
    "yake mabaya, Wala",
    "hasengenyi jirani yake,",
    "Wala haonei wivu kitu chochote.",
    "4. Mtu huyu ndiye",
    "mtakatifu, Hatoi",
    "pesa yake ili apate",
    "riba,",
    "Wala hakutwaa rushwa",
    "amwangamize, Asiye na",
    "hatia machoni pake.",
  ] },
  { no: 52, title: "TUTAKAPOFIKA ZAYUNI", lines: [
    "1. Tutakapofika",
    "zayuni, Mji",
    "wa raha na",
    "amani,",
    "Tutapata",
    "furaha tele,",
    "Shida",
    "zitasahaulika.",
    "Nakuinua sana Bwana,",
    "Kwa kunifanya mwana",
    "wako, Ndipo nitakuwa",
    "mmoja,",
    "Wa kuridhi ufalme wako.",
    "2. Nani mwingine",
    "astahili,",
    "Kuupokea",
    "utukufu,",
    "Aliyejawa na",
    "Fadhili,",
    "Hakuna mwingine ni wewe x2",
    "3. Niseme nini",
    "mbele zako,",
    "Isipokuwa",
    "nikusifu,",
    "Kwa kuwa wema",
    "wako kwangu,",
    "Nitasimulia milele.",
    "4. Ninatamani",
    "siku hiyo,",
    "Nitakapokuon",
    "a Baba, Tuishi",
    "nawe siku",
    "zote,",
    "Na nitatosheka milele. X2",
  ] },
  { no: 53, title: "ABARIKIWE BWANA", lines: [
    "1. Mkono wake Bwana",
    "ule wa kuume,",
    "Umetukuka kote",
    "watenda makuu,",
    "Abarikiwe bwana ametupa",
    "nuru, Ametufungulia",
    "malango ya haki",
    "2. Huimwaga barafu",
    "kama ni majivu, Ndiye",
    "atoaye theruji kama",
    "sufu x2",
    "3. Ni heri",
    "kumkimbilia",
    "Elohim, Kuliko",
    "kuwatumainia",
    "wakuu.",
    "4. Tumsifu kwa matari na kucheza",
    "Na kila mwenye pumzi amusifu Bwana x2",
  ] },
  { no: 54, title: "YAHSHUA NI NGOME", lines: [
    "1. Yahshua ni ngome,",
    "ngome imara, Ukiwa",
    "naye hautashindwa,",
    "Ukimfuata hutakosea,",
    "Njia ya zayuni utafika",
    "Ni msaada wa",
    "karibu, Kwa wale",
    "wamtumainio Ni",
    "kimbilio la haraka,",
    "Kwa wale",
    "wanaoteseka.",
    "2. Unaposongwa na",
    "majaribu, Na shida",
    "nyingi",
    "kukuandama, Usife",
    "moyo anakuona,",
    "Ako tayari akupiganie.",
    "3. Hata watu wakikudharau,",
    "Na wajitenge mbali",
    "na wewe, Ujipe",
    "moyo uendelee,",
    "Kwa kuwa Yahshua anakupenda.",
    "4. Jifundishe uwe",
    "kama Yahshua,",
    "Upende hata adui",
    "zako,",
    "Na usijilipishe kisasi,",
    "Utende wema kwa watu wote.",
  ] },
  { no: 55, title: "YAHSHUA YU MWEMA", lines: [
    "1. Yahshua yu",
    "mwema,",
    "Maishani",
    "mwangu,",
    "Ulikuja",
    "ukafa, Tupate",
    "wokovu.",
    "Yahshua ulishinda, Kwa",
    "kuvumilia, Tujaze roho",
    "wako, Tuweze kushinda.",
    "2. Tunakushuk",
    "uru, Kwa",
    "Fadhili",
    "zako, Na",
    "rehema",
    "zako,",
    "Kwetu",
    "wanadamu.",
    "3. Kote duniani,",
    "Hakuna kama",
    "wewe, Wewe",
    "ndiwe",
    "mungu, Na",
    "tena mfalme.",
    "4. Ninayatama",
    "ni, Makao",
    "ya zayuni,",
    "Utakaporudi",
    ", Bwana",
    "nikumbuke.",
  ] },
];
